### ISSUE TITLE
IE11 issue on Update

### ISSUE THREAD

**Issue by bytewiz** [jscottsmith/react-scroll-parallax#10]
```
this.updateElement = function (element, options) {
        // gets the index of the element to update based on id
        var index = elements.findIndex(function (el) {
            return el.id === element.id;
        });
```
`Object doesn't support property or method 'findIndex'`

When it runs the updateElement function in IE11 for me I am receiving the error above.
and that breaks the entire site for me.

**Comment by jscottsmith** [comment]
@bytewiz thanks, I'll work on publishing a release that supports IE. If you are blocked by this you should be able to include a polyfill like the one provided by [babel](http://babeljs.io/docs/usage/polyfill). Regardless, I'll try to provide a fix soon since it should be pretty easy.

**Comment by jscottsmith** [comment]
Puplished [v1.1.1](https://github.com/jscottsmith/react-scroll-parallax/releases/tag/v1.1.1)

**Comment by bytewiz** [comment]
@jscottsmith thanks 👍 will test it out
