### ISSUE TITLE
Inner Layer Image filter

### ISSUE THREAD

**Issue by joserenev** [jscottsmith/react-scroll-parallax#104]
## Trouble With Implementation

Describe the trouble you are having considering the following:

* What is the expected behavior of your implementation?
 I am trying to add image filters to the inner layer only but as I add them in the style prop for ParallaxBanner it applies it to whatever children I pass inside the component for example text. I would like to know how to apply that to the inner layer of the image.

**Comment by jscottsmith** [comment]
@joserenev You could probably omit the `layer.image` and instead use `layer.children` to also recreate the image, so that text and image are siblings and the text will not inherit the css filter. 

Example:

```javascript
<ParallaxBanner
  layers={[
    {
      amount: 0.2,
      children: (
        <>
          <div
            style={{
              backgroundImage: `url(${image})`,
              backgroundPosition: 'center',
              backgroundSize: 'cover',
              position: 'absolute',
              top: 0,
              left: 0,
              right: 0,
              bottom: 0,
              filter: 'blur(10px)',
            }}
          />
          <p>You text</p>
        </>
      ),
    },
  ]}
/>
```

**Comment by joserenev** [comment]
Great it worked. Probably it would be good to see more examples in the README for the other props as they might cause confusion in implementation. Thanks!
