### ISSUE TITLE
Can't click child button in <ParallaxBanner>

### ISSUE THREAD

**Issue by EvilBook** [jscottsmith/react-scroll-parallax#105]
Can't click on children inside the ParallaxBannertags.
eg. >ParallaxBanner< >a href='whatever.com'< Click me >/a< >/ParallaxBanner<
can't click the link child.
Can you help me?

disregard the inverted arrows.

**Comment by jscottsmith** [comment]
Sorry, I need more information to diagnose the issue. But it sounds like some styling is interfering with the pointer events on the element. Send me a live link to your project, or a repo and I can help you further. Closing this until then.
