### ISSUE TITLE
What's not described in documentation.

### ISSUE THREAD

**Issue by pcdependency** [jscottsmith/react-scroll-parallax#109]
**SMALLER QUESTIONS:**

What are the left and right or first and second values of the x and y array props for Parallax stand for?

**BIGGEST QUESTIONS:**

What "Element" does the Providers scrollContainer prop take? A ref or a className of your overflow container?

Does this work with redux or only with contextAPI, there are many libraries that only work with a specific State tool.

If your scroll container is in a child component but you wrap your top-level component in the provider, do you have to save a ref up to the global state?

**Comment by jscottsmith** [comment]
> What are the left and right or first and second values of the x and y array props for Parallax stand for?

First value is the start offset as the element enters the view, second is ending offset as the element leaves the view.

> What "Element" does the Providers scrollContainer prop take? A ref or a className of your overflow container?

HTML Element

> Does this work with redux or only with contextAPI, there are many libraries that only work with a specific State tool.

Works with the context api that is shipped with React. 

> If your scroll container is in a child component but you wrap your top-level component in the provider, do you have to save a ref up to the global state?

Use a component as the scroll container, something like https://github.com/jscottsmith/react-scroll-parallax/blob/develop/stories/ScrollContainer.js
