### ISSUE TITLE
ParallaxBanner with scrollContainer only works with ref in state

### ISSUE THREAD

**Issue by pcdependency** [jscottsmith/react-scroll-parallax#110]
ParallaxBanner with a scrollContainer only works when you set the ref.current to the state and then pass the state variable to the scrollContainer prop. 

Here an example: https://codesandbox.io/s/spring-butterfly-e5006?file=/src/App.js

**Comment by jscottsmith** [comment]
take a look at this, it may help: https://github.com/jscottsmith/react-scroll-parallax/blob/develop/stories/ScrollContainer.js
