### ISSUE TITLE
Unusable mobile performance

### ISSUE THREAD

**Issue by pcdependency** [jscottsmith/react-scroll-parallax#111]
## Expected Behavior

Framerate higher than low 10s or 5s

Describe what should be happening.

1) First, expanded props on the ParallaxBanner only works on 1 layer.

2) Mobile performance with this library is probably the worst I've seen out of all the other parallax libraries. If you are running anything other than a few small images and some text, the mobile performance becomes unusable.

## Actual Behavior

The parallax turns jerky.

What went wrong? Provide code snippets, demo links, or repositories demonstrating the broken behavior.

Here a video: https://i.imgur.com/RNxMyGI.mp4

It shows 4, 2k-4k images, all added up to 5mb in size together, with major performance issues. This is running on an iPhone 6s on the chrome browser, safari was the same.

## Steps to Reproduce the Problem

npm install react-scroll-parallax,
build a simple app,
add a few images

**Comment by jscottsmith** [comment]
bummer, i would suggest you read this: https://github.com/jscottsmith/react-scroll-parallax#psa
