### ISSUE TITLE
Feature request: Disable when aligned/reaches scroll point

### ISSUE THREAD

**Issue by Mladja89** [jscottsmith/react-scroll-parallax#113]
## Feature Request

Can we have a feature for parallax effect to be disabled once multiple elements are aligned or when reaches certain point in scrolling?

**Comment by rtrvrtg** [comment]
Or possibly allow for multiple x or y properties per `<Parallax>` element, so you can do some sort of easing for the parallax effect when you reach particular scroll points.

**Comment by brunoreis** [comment]
I think a map of keyframes would aggregate all those scenarios: 
```
x: {
  "0": -20, // x will start on -20%
  "30":  0, // when the page scroll 30%, x will be 0
  "70": 0,  // x will keep at 0 until the page is scrolled 70%
  "100": 50 // from 70 to 100 x will scroll 100%
}
```

**Comment by jscottsmith** [comment]
Planning to support something like this in the new version #123
