### ISSUE TITLE
Update for React v.17

### ISSUE THREAD

**Issue by evengene** [jscottsmith/react-scroll-parallax#116]
Hello, 
I'm experiencing issues with this plugin, it seems that it doesn't support newer versions of React.
I'm using **Gatsby v.3.3.1** and **React v.17.0.1**
Could you please help me with that?
Thank you

**Comment by jscottsmith** [comment]
Updated the peer dependency to include React 17 and published [`v2.4.0`](https://github.com/jscottsmith/react-scroll-parallax/tree/v2.4.0). Let me know if this doesn't fix the issue.
