### ISSUE TITLE
The positioning of a direct sibling to a parallax Element.

### ISSUE THREAD

**Issue by iremlopsum** [jscottsmith/react-scroll-parallax#12]
I have applied parallax to only one element on a website, and I have a problem with keeping the position of the sibling right under it normal.

See a screen recording: https://cloudup.com/c_pkJK-UDrM

The element changes height on resize, but the parallax container keeps the same dimensions, I tried applying update on resize as well, but that does nothing.

What's the expected way of dealing with this?

**Comment by iremlopsum** [comment]
So, I fixed it by wrapping all of the elements withing `Parallax` so that they would be as a single unit. Now the problem is that I have loads of empty space at the bottom the website before the footer.

Same question, how to deal with this?

**Comment by jscottsmith** [comment]
@iremlopsum Sure, but I'll need to see the code to help you out. Set up an example of what you are trying to do or give me access to a repo and I'll take a look. This lib doesn't set any heights on containers, it only adds transforms to the inner parallax div. All other styles should come externally or from classes. So without seeing those I can't help debug.
