### ISSUE TITLE
[Support] Examples are too complex

### ISSUE THREAD

**Issue by nukec** [jscottsmith/react-scroll-parallax#121]
There should be simple examples with divs on how to move the divs up and left. Storybook has good examples, but source code is again too complex. I suggest you do example per component, with separation of concerns and do simple hardcoded examples so it can be understood quickly. at the moment it's very complex to understand how different values work.

**Comment by jscottsmith** [comment]
Thanks for the input, I agree. Hoping to get some work done clarifying common issues soon. Cheers.
