### ISSUE TITLE
Could not find `react-scroll-parallax` context value.

### ISSUE THREAD

**Issue by sirshurak** [jscottsmith/react-scroll-parallax#125]
How to properly handle provider with SSR ? I'm having this throwing error.

https://github.com/jscottsmith/react-scroll-parallax/blob/df1b1cc96d4f6a8041299d1015674e03270fc989/src/components/useController.js#L9

I've verified that when `window` is not defined the context is returned `null`

https://github.com/jscottsmith/react-scroll-parallax/blob/df1b1cc96d4f6a8041299d1015674e03270fc989/src/components/ParallaxProvider.js#L10

**Comment by jscottsmith** [comment]
@sirshurak ya it should not throw in this case. I published a patch `react-scroll-parallax@2.4.2`. Please try this version and see if the error is resolved. Thanks!
