### ISSUE TITLE
parallaxController.update

### ISSUE THREAD

**Issue by lineldcosta** [jscottsmith/react-scroll-parallax#13]
Hello,

Is there any examples for parallaxController.update, Since this is not working for me.

I just tried below.
in render
<ParallaxProvider ref={r => this.parallax = r}>
then
after scroll function i just call

this.parallax.parallaxController.update();

is this right?

**Comment by jscottsmith** [comment]
Not sure what you are trying to do based on that. Care to share a repo or more details about the issue are trying to solve? For the most part, you should never have to call `parallaxController.update()` unless the page layout has changed for some reason other than a resize.
