### ISSUE TITLE
Failed to create the resize observer in the ParallaxContoller

### ISSUE THREAD

**Issue by princejoogie** [jscottsmith/react-scroll-parallax#137]
## Expected Behavior

no warnings when running tests with jest

## Actual Behavior

bunch of console.warn are printed when running tests

```
console.warn
    Failed to create the resize observer in the ParallaxContoller
```

![image](https://user-images.githubusercontent.com/47204120/155836659-6e6b3730-dde5-44f3-a9f8-c8c543615296.png)

## Steps to Reproduce the Problem

1. add `ParallaxProvider` in `_app.tsx` then add a `Parallax` component to one of the elements.
2. create a simple unit test (jest)
   ```js
	  beforeEach(() => {
	    render(
	      <ParallaxProvider>
	        <Home />
	      </ParallaxProvider>
	    );
	  });

	  it("renders facebook button", () => {
	    const fbButton = screen.getByTestId("jumbotron-facebook-button");
	    expect(fbButton).toHaveTextContent("Facebook group");
	  });
   ```
3. run tests with jest

## Environment

* Version: 3.0.3
* Platform: Windows
* Browser: Firefox
* Framework: NextJS

**Comment by jscottsmith** [comment]
It's a warning, so you can just ignore it but if you want to fix it add just a Resize Observer mock to your Jest . This API is not available in Jest DOM by default. See this for an example: https://github.com/jscottsmith/parallax-controller/blob/master/src/setupTests.ts

**Comment by petertflem** [comment]
I also get the log statement, but when the site is live (saw it on staging). Is it safe to ignore i production too?
<img width="305" alt="image" src="https://user-images.githubusercontent.com/5292940/232058171-b2e05fa2-137b-47a5-b63d-b6c1b7d89940.png">

**Comment by jscottsmith** [comment]
@petertflem hmm, seems strange -- [this should only show on browsers](https://github.com/jscottsmith/parallax-controller/blob/master/src/classes/ParallaxController.ts#L150) that do not support the [ResizeObserver API](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#browser_compatibility) but most modern browser do.

Are you on an old version of Chrome?

Regardless, you can ignore it. The event help update cache when layout shifts, but won't break without it.

**Comment by petertflem** [comment]
@jscottsmith Hm, I probably was, but my memory is fuzzy. Might have been testing on iOS 13 with Safari or Chrome, we had some other errors there. In fact, I am pretty sure I was. Either Chrome 92, but likely Safari 13, and the ResizeObserver API was introduces in 13.1, it looks like.

Thanks!
