### ISSUE TITLE
CSS transforms handled by react-scroll-parallax are getting reset.

### ISSUE THREAD

**Issue by rahuuzz** [jscottsmith/react-scroll-parallax#139]
## Actual Behavior (bug)
state update is causing parallax to reset to initial after reaching endScroll.
An example for demo code [can be found here](https://codesandbox.io/s/gracious-galois-p4ozcp)

## Expected Behavior
Expecting to prevent resetting the transformations done by react-scroll-parallax after endScroll position.

## Steps to Reproduce the Problem

1. Use the above code sandbox link. (Or create some parallax components and trigger some state update (i did it in onProgressChange)) 
2. Scroll till the parallax completes ( scroll position = 460)
3. See that the transformations are reset (on reaching scroll position 461)

## Environment
* Framework: next-js
* Node Version: 14
* Platform: macOS
* Browser: Google Chrome 98.0.4758.109

**Comment by jscottsmith** [comment]
Thanks for the easy reproduction -- I'll work on a fix this week.

**Comment by jscottsmith** [comment]
Fix published in [v3.0.4](https://github.com/jscottsmith/react-scroll-parallax/releases/tag/v3.0.4). Let me know if there's any other issue.

**Comment by rahuuzz** [comment]
Tried updating to 3.0.4 still havent solved the issue. [preview](https://p4ozcp.sse.codesandbox.io/)

**Comment by jscottsmith** [comment]
ahh, remove the lockfile, the issue was in the dependency and it's probably still using the old version. https://codesandbox.io/s/vigilant-hofstadter-rhthqo?file=/package.json
