### ISSUE TITLE
Animations lag / jitter on iOS

### ISSUE THREAD

**Issue by sourcelocation** [jscottsmith/react-scroll-parallax#144]
**Describe the bug**

The example ParallaxBanner lags on iOS.

**To Reproduce**
1. Go https://react-scroll-parallax-v3.surge.sh/?path=/story/components-parallaxbanner--with-a-single-background on iOS (Xcode Simulator or real phone)
2. Scroll

**Expected behavior**
The animations are expected to be smooth

**Screenshots**
[Video](https://user-images.githubusercontent.com/52459150/158765767-624ae190-dc12-40db-90ac-39f296aba051.mov)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Safari
 - Version: on iOS 15, latest

**Smartphone (please complete the following information):**
 - Device: iPhone 
 - OS: iOS 15
 - Browser Safari
 - Version latest

**Additional context**
Providing more information than the previous issue had.

**Comment by jscottsmith** [comment]
Ya, this is unfortunate issue with most scroll effects on mobile. 
I recommend disabling or limiting the effect -- in this case of the storybook banner decrease the movement.

> Disable most (or all) scroll effects on mobile. Mobile devices optimize for best battery life and animation performance will often be degraded.

More info here on [performance](https://parallax-controller.damnthat.tv/docs/performance).

If you have recommendations on how to improve performance on mobile please submit a PR. Thanks!
