### ISSUE TITLE
GIF Animation

### ISSUE THREAD

**Issue by CodeDoctorDE** [jscottsmith/react-scroll-parallax#153]
Hello, I found your library and found it very useful.
But I have one issue I'm facing with: How can I animate a gif while scrolling?
Like here https://www.apple.com/macbook-pro-14-and-16/ where the mac is opened when you scroll

**Comment by jscottsmith** [comment]
You won't be able to create this effect with this library.

Effects like the one on Apple's website are not created with GIFs but with a large sequence of images (jpg/png) that are displayed based on scroll position.

Example of such effect with code. https://codepen.io/jacob_124/pen/dyydWbB

I'm not aware of any libraries that are able to create this effect but you can try and search for one or create it on your own.

**Comment by CodeDoctorDE** [comment]
Thanks for your tip. https://react-scroll-parallax.damnthat.tv/docs/examples/how-it-works#progress-is-relative-to-the-view maybe I can integrate your library to get the progress
