### ISSUE TITLE
Increasing size

### ISSUE THREAD

**Issue by ishtiaqSamdani** [jscottsmith/react-scroll-parallax#158]
It will be very nice if we have a attribute which can control the size of parallax layer component

**Comment by jscottsmith** [comment]
Open to new features but you'll need to elaborate:

What "size" are you talking about? 
Do you mean the layers of the `ParallaxBanner` component? 
Can you provide some examples with code of the changes you're proposing and why? 

Let me know so I can consider how to support the request.
