### ISSUE TITLE
little yanking in Chrome, more noticeable on Safari 

### ISSUE THREAD

**Issue by csantiago132** [jscottsmith/react-scroll-parallax#16]
Hi and first of all, thank you for this plugin!  quite frankly its wonderful to work with! 

Just wanted to point out that its yanking a little in both chrome and safari but more noticeable on safari. when you scroll down, the pages kinda rethinks smooth scrolling and thats when it begins to yank a little. right now, I only have it wrapped inside an `<h1>` tag, quoting you 

> but if you do (like I did) and you use this package try and use it responsibly...

anyways, just wanted to give you a heads up and ill patiently wait for any help if you can, in the meantime, ill keep trying to troubleshoot on my end.

i tried rolling back to `1.1.0` but same behavior.

again, great job and i appreciate the plugin

**Comment by csantiago132** [comment]
ok so after digging around, seems like css like this starts the yanking

    .css file
    ...
    background: url('../path/to/image.png');
    background-repeat: no-repeat;
    background-attachment: fixed; // <-- maybe this?
    ...

I took it out and its performing better but still. thats on version `1.1.1`

I also noticed that it only happens when the webpage is fullscreen; if you turn on web inspector, scrolling works like butter. if webpage gets back to normal size, the little yanking begins again.

<img width="837" alt="screenshot 2017-12-12 22 10 50" src="https://user-images.githubusercontent.com/5726971/33921450-78977a5a-df89-11e7-9735-6c9899c69302.png">
<img width="611" alt="screenshot 2017-12-12 22 11 12" src="https://user-images.githubusercontent.com/5726971/33921451-78a711fe-df89-11e7-8ff3-9e2399a6b53b.png">

**Comment by jscottsmith** [comment]
@csantiago132 Hah, thanks for the report. I'd like to look into it further -- possible to share the repo with me?

I expect all `^1.0.0` to perform about the same. Nothing was changed in terms of optimizing jank or that would impact performance, so don't worry about rolling back. It could be related to the setup and I think you are on the right track in noting that removing `background-attachment: fixed` makes it perform better. That type of css can cause major jank in certain scenarios. Window size can also make a difference, especially on large hd screens.

But honestly I'm not sure and it could be related to other things. I've certainly noticed some jank when testing things on my end so it's not to say it is _not_ this package. But If I can check out your code I might have some further ideas to help troubleshoot or optimize.

If you can't share the code, I would try recording a profile in Chrome to see if any frame updates are labeled janky or just dropping far below 60fps. They'll be flagged red if it takes the browser longer than 16ms to paint.

**Comment by csantiago132** [comment]
@jscottsmith hey thanks for the quick reply (and forgive my tardiness). Let me finish up clearing stuff up and be back to my computer. also, all of a sudden, the plugin seems to be working fine so I don't know if it was a cache issue or if rolling back some dependencies I updated made it better.

**Comment by jscottsmith** [comment]
Closing, but feel free to send over the code if you start encountering issues again and want me to take a look.

**Comment by csantiago132** [comment]
@jscottsmith sorry for the delay, I was out of town and getting back to my computer. I found the reason and it's totally unrelated to the plugin; was a third-party library being loaded but many thanks for the quick support and help. again, great plugin!
