### ISSUE TITLE
How to implement breakpoint for startScroll and endScroll

### ISSUE THREAD

**Issue by aryabeth** [jscottsmith/react-scroll-parallax#167]
Can we add break point value for startScroll and endScroll?

i'm implement this code but it doesn't work on mobile and HD screen, i think because scroll value is different on mobile and HD Screen.

 ```
<Parallax
    translateX={[-10, 0]}
    opacity={[0.2, 1]}
    startScroll={4000}
    endScroll={4800}
  >
        <MyComponentHere />
</Parallax> 
```

**Comment by jscottsmith** [comment]
@aryabeth `startScroll` and `endScroll` will change dramatically based on screen size. You must calculate them yourself and proved different values based on your requirements. This is kind of a last resort for users with highly custom needs.

You're probably better off using a `targetElement` positioned with CSS. This way it will resize and update with the browser window and you won't need to manually calculate the `startScroll`, `endScroll`.

Some examples and links to the docs:

https://codesandbox.io/s/react-scroll-parallax-target-element-m635p5
https://react-scroll-parallax-v3.surge.sh/?path=/story/components-parallax-vertical-scroll--with-defined-target-element
https://react-scroll-parallax.damnthat.tv/docs/usage/parallax-props#configuration-props
