### ISSUE TITLE
All animations starts on top scroll

### ISSUE THREAD

**Issue by Nahay** [jscottsmith/react-scroll-parallax#169]
Hi, 
I tried to animate elements on a horizontal website. I modified the scrollContainer so the animations work but they all start the same time (on scroll 0, onEnter event log for each animations). Means when we reach it in viewport animation is already ended.

Here is the code : https://codesandbox.io/s/charming-silence-kw55ge?file=/src/App.js

**Comment by jscottsmith** [comment]
There's some odd styling that is conflicting with the parallax setup. I've commented it out and also set `scrollAxis="horizontal"` in the provider and things seem to work.
