### ISSUE TITLE
Question: why warn when min is greater than zero and max is less than zero?

### ISSUE THREAD

**Issue by lsirivong** [jscottsmith/react-scroll-parallax#17]
What the downside is of setting the offset min > 0 and offset max < 0?

With this setting I'm getting a warning

```
<Parallax
  offsetYMin={`25%`}
  offsetYMax={`-50%`}
  slowerScrollRate
>
  {numeral}
</Parallax>
```

```
Warning: Failed prop type: [offsetYMax] in Parallax is less than zero. [offsetYMax] must be greater than or equal to zero.
```

My intent was to have the content slide upwards while scrolling down the page. Is there an alternative way to create a reverse the parallax direction?

**Comment by lsirivong** [comment]
Nevermind! I realize now that's what `slowerScrollRate` is for

**Comment by jscottsmith** [comment]
Hah, I was just about to explain it. Yes, `slowerScrollRate` just flips those offset values. In hindsight I think it's poorly named and should have just allowed any values in the min/max offsets and not have added that prop. In v2 I've done just that.

Glad you figured it out. I'll update the readme to clarify this behavior and hopefully prevent further confusion.

**Comment by eballeste** [comment]
version 2?

**Comment by jscottsmith** [comment]
Ya, working on it. I'll try and cut an alpha soon. 

https://github.com/jscottsmith/react-scroll-parallax/tree/next
