### ISSUE TITLE
Allow users to disable parallax from ParallaxProvider

### ISSUE THREAD

**Issue by ArthurSangouard** [jscottsmith/react-scroll-parallax#183]
I'm looking to disable parallax on mobile, but it seems that the way to do this is to toggle the _disabled_ prop in every instance of **useParallax** or **Parallax**.
Letting users enable it from the root ParallaxProvider component would greatly simplify this.

**Comment by jlarmstrongiv** [comment]
That would also be helpful for accessibility for users who [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
