### ISSUE TITLE
Option to animate css

### ISSUE THREAD

**Issue by vestimir** [jscottsmith/react-scroll-parallax#20]
Is it possible to use ParallaxProvider, or Parallax to animate certain CSS property – for example adding fade in/out via `opacity`? 

Is there a method, or callback that can be used to calculate some kind of a ratio?

**Comment by jscottsmith** [comment]
Not in v1, sorry. I've been working on a [v2](https://github.com/jscottsmith/react-scroll-parallax/tree/v2) that supports [opacity](http://react-scroll-parallax.surge.sh/?knob-A%3A%20Opacity%201=1&knob-A%3A%20Opacity%202=0&knob-B%3A%20Opacity%201=0&knob-B%3A%20Opacity%202=1&selectedKind=%3CParallax%3E&selectedStory=with%20opacity%20props&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs) and you can access the progress of an element in the viewport to do custom effects.

Track progress of v2 [here](https://github.com/jscottsmith/react-scroll-parallax/issues/15).

**Comment by vestimir** [comment]
Will do, thanks for the awesome plugin!
