### ISSUE TITLE
It always run onEnter at the beginning.

### ISSUE THREAD

**Issue by CuongGuti** [jscottsmith/react-scroll-parallax#204]
## Bug

It always run onEnter at the beginning. Can you check please. Thank you.

Example:

`useParallax({
    translateX: ['-50%', '0%'],
    opacity: [0, 2],
    onEnter: () => {
        // always run this when init or page load.... please help me to fix.
    },
    speed: 0,
}),`

**Comment by jscottsmith** [comment]
Happy to help but I'll need a Codesandbox that reproduces the bug.

Fork this sandbox and demo the bug please:

https://codesandbox.io/s/react-scroll-parallax-template-x6lus4
