### ISSUE TITLE
Add `disabled` prop to `ParallaxProvider`

### ISSUE THREAD

**Issue by dan-cooke** [jscottsmith/react-scroll-parallax#206]
I have seen a bit of buzz about disabling the Parallax on mobile - quite common. 

Currently the only way to do this to create a proxy/wrapper component around this libraries `Parallax` component.

But it would be much more convenient to allow consumers to just disable this in one place, the `ParallaxProvider`

**Comment by jscottsmith** [comment]
Agreed, see #183. Just a little behind on working on this lately.
