### ISSUE TITLE
Element with parallax applied always transformed along Y axis when scroll position is 0 

### ISSUE THREAD

**Issue by hamishtaplin** [jscottsmith/react-scroll-parallax#21]
Sorry for the long-winded title. I'm using this library (awesome work btw) to implement a parallax header similar to your example: https://codepen.io/jscottsmith/pen/aVBvGj

My issue is that I want the header to not be transformed at all until the user scrolls, so it sits flush to the top of the viewport. However, even when `window.scrollY` is `0` there's always some `transformY` being applied. You can see this even in the codepen above so I'm sure it's not something I'm doing wrong.

Is this by design?

**Comment by jscottsmith** [comment]
Hmm, it depends on where the element is positioned relative to the viewport window. Would you mind sharing your code with, or an isolated demo of what your doing? Then I can confirm if it's expected behavior or if something else is up.

**Comment by hamishtaplin** [comment]
Hi. Here's a preview of what I mean: https://5a8402887b6ee82bc4420066--blacklabfilms.netlify.com/

**Comment by jscottsmith** [comment]
Thanks. Cool site.

Yes this is expected. The way I'm getting around it it is by expanding the height of the parallax element by the total amount of offset. Given a `-10%` min offset and `10%` max offset, you'd need to expand the height by 20% and position it correctly so the edges are never visible. I'm doing that [here in the src](https://github.com/jscottsmith/react-scroll-parallax/blob/master/src/components/ParallaxBanner.js#L44) for `<ParallaxBanner>`. I'm also doing something similar in the CodePen originally linked, check the Scss.

You'll have to handle this manually, as `<ParallaxBanner>` isn't setup to handle video. But I'm think it should be an easy update to allow custom children for each `layer`. I'll look into supporting this.

Let me know if this helps.
