### ISSUE TITLE
Stop the effect at a given position

### ISSUE THREAD

**Issue by hawret** [jscottsmith/react-scroll-parallax#212]
You can already decide when the animation begins with `targetElement` & `rootMargin`, but not when it should end.
The option `startScroll, endScroll` isn't friendly with responsiveness.
The progress could be paused when reaching a certain point and then resumed when scrolling up.

```ts
onProgressChange: n => {
  if (n > 0.55) {
     parallax.controller.pause()
  } else {
     parallax.controller.resume()
  }
}
```
or `endScroll` could indicate the progress e.g. `0.55`

Is there a hack way that I could do right now?

Related https://github.com/jscottsmith/react-scroll-parallax/issues/133

**Comment by jscottsmith** [comment]
`targetElement` could also be used to end an animation early, just depends how the target is positioned. 

It would help to know the exact effect that you're trying to achieve, then I could show you how it might be done with this library, or advise to use something else instead.

**Comment by hawret** [comment]
Thank you for the quick answer :)

The green block should stop at the end of the purple
https://codesandbox.io/s/react-scroll-parallax-target-element-forked-wy97bc?file=/src/styles.css

**Comment by jscottsmith** [comment]
Something like this?

https://codesandbox.io/s/react-scroll-parallax-target-element-stop-early-nev746?file=/src/App.tsx

**Comment by hawret** [comment]
It should start in the middle (my example) and end at the bottom of purple

**Comment by hawret** [comment]
This is a good example https://react-scroll-parallax-examples.vercel.app/
At the end, how would you stop the animation when the circles are aligned?

**Comment by hawret** [comment]
That works, thanks! :))

A better API for this would be `startScroll` accepting `self` and add two others: `duration` and `offset`
```ts
// before translateY changes the original position
// I think `window.addEventListener('load', ...)` is required here
const start = window.pageYOffset + element.getBoundingClientRect().top
...
startScroll: (start - offset) 
endScroll: (start - offset) + duration
```
