### ISSUE TITLE
Could not find `react-scroll-parallax` context value. Please ensure the component is wrapped in a <ParallaxProvider>

### ISSUE THREAD

**Issue by burasov-artyom** [jscottsmith/react-scroll-parallax#233]
Good afternoon.
I can't use this library after moving the project from CRA to Next.js. I get an error that the provider cannot be imported, although it is added to _app.jsx.

Has anyone encountered a similar problem?

_app.jsx
```
const App = ({ Component, pageProps }) => {
    return (
        <ParallaxProvider>
            <WagmiConfig config={wagmiConfig}>
                <ScrollToTop />

                <ApolloProvider client={defaultClient}>
                    <Provider store={store}>
                            <Component {...pageProps} />
                    </Provider>
                </ApolloProvider>
            </WagmiConfig>
        </ParallaxProvider>
    )
}
```

parallax component
```
import { useParallax } from "react-scroll-parallax";

const Bubble = ({ isLeft, className, children }) => {
    const { ref } = useParallax({
        rotate: isLeft ? [0, 20] : [0, -20],
        translateY: [40, -40]
    });

    return (
        <div className={className} ref={ref}>
            { children }
        </div>
    );
};

export default Bubble;
```

List of related npm package versions
```
"next": "^14.0.2",
"react-scroll-parallax": "^3.4.3",
```

**Comment by raRaRa** [comment]
I have a PR that should fix these issues: https://github.com/jscottsmith/react-scroll-parallax/pull/234

**Comment by jscottsmith** [comment]
Please try [v3.4.4](https://github.com/jscottsmith/react-scroll-parallax/releases/tag/v3.4.4) to see if this issue is resolved.

**Comment by burasov-artyom** [comment]
Problem resolved. Thanks a lot

**Comment by burasov-artyom** [comment]
After fixing the problem, the following error is spammed in the console

![изображение](https://github.com/jscottsmith/react-scroll-parallax/assets/47752247/1ca784a3-8bcc-41d8-8a13-701bb8ca78a7)

**Comment by jscottsmith** [comment]
@burasov-artyom Can you provide some steps to reproduce? Guessing this happens after making changes, but I haven't been able to verify on my end.

**Comment by raRaRa** [comment]
I'm having the same issue on certain pages that don't have any Parallax components. Maybe that could be related to the issue? It works if I start on a page that has Parallax components and then navigate to another one without any with client-side routing.

**Comment by raRaRa** [comment]
Well, maybe not the same error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at ParallaxController._handleScroll (parallax-controller.esm.js:1064:1)
```

**Comment by jscottsmith** [comment]
Thanks, I was able to reproduce the error. I'll look into it.

**Comment by jscottsmith** [comment]
Alright, give [`v3.4.5`](https://github.com/jscottsmith/react-scroll-parallax/releases/tag/v3.4.5) a try.

**Comment by burasov-artyom** [comment]
Great! Works without errors
