### ISSUE TITLE
如何解决滚动时结束了，页面会抖动的问题？

### ISSUE THREAD

**Issue by renjiali** [jscottsmith/react-scroll-parallax#254]
How to solve the problem that the page will shake when scrolling is over? Sometimes I stop scrolling, but the page will suddenly scroll up a very small distance, and then resume, it is very uncomfortable, it feels very slow

如何解决滚动时结束了，页面会抖动的问题？有时候停止滚动了，但是页面会突然向上滚动很小的距离，再恢复一下，很难受，就感觉很卡顿

**Comment by jscottsmith** [comment]
I can't help you without an example of the issue.
