### ISSUE TITLE
Can I do static parallax picture?

### ISSUE THREAD

**Issue by OptimaLPro** [jscottsmith/react-scroll-parallax#258]
Hey!

I wonder if i can do that the parallax has no speed, exactly like that:

https://www.thelightphone.com/

that the first section and the second are like "static", and also the second section is static.
The third section is "normal" without parallax.

If you have Codesandbox it will be amazing.

thanks!

**Comment by jscottsmith** [comment]
Sorry for delayed response @OptimaLPro. You can do this with plain old CSS. No need for a parallax library.

[CodeSandbox example of this with only CSS](https://codesandbox.io/p/sandbox/l6hk7z?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm39clhb500063b6m14l9jthe%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm39clhb400023b6m7vrljya3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm39clhb400033b6mwqu4bt1g%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm39clhb400053b6mn9wsxroe%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm39clhb400023b6m7vrljya3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm39clhb400013b6mu9uaod8k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522cm39clhb400023b6m7vrljya3%2522%252C%2522activeTabId%2522%253A%2522cm39clhb400013b6mu9uaod8k%2522%257D%252C%2522cm39clhb400053b6mn9wsxroe%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm39clhb400043b6muis3trzg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cm39clhb400053b6mn9wsxroe%2522%252C%2522activeTabId%2522%253A%2522cm39clhb400043b6muis3trzg%2522%257D%252C%2522cm39clhb400033b6mwqu4bt1g%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm39clhb400033b6mwqu4bt1g%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
