### ISSUE TITLE
Choppy parallax on safari

### ISSUE THREAD

**Issue by CYB3RL1F3** [jscottsmith/react-scroll-parallax#26]
Hi,

I'm using your component in an app I'm currently working on, but it's actually choppy on scroll... There are some animations run in the same time, but it works perfectly on Chrome. Firefox is a bit choppy too. 

I read on the web that it could be solved with material acceleration. I tried to set up on .parallax-inner the two followings : 

```
perspective: 1000;
backface-visibility: hidden;
```

But that hasn't any effect... Any clue why it's so slow and choppy ? And how to solve it ?

Thanks a lot :)

**Comment by jscottsmith** [comment]
> Any clue why it's so slow and choppy ? And how to solve it ?

Nope. Hard to know based on this information alone. I also doubt GPU hacks will help much. Most likely it's due to how the component is being used or other heavy animations/processes that are running on the page.

I'll need to see your particular setup (repo, or live site) to provide any useful help/advice.

**Comment by CYB3RL1F3** [comment]
Yep. There is sadly an heavy process asked by the customer : a magnetic scroll. 

https://github.com/CYB3RL1F3/react-magnetic-scroll

And I'm also using a sticky component... I optimized a bit the magnetic scroll, and now it's perfect on Firefox, but it remains slowly on Safari. 

The parallax components are set in a container that hosts all parallax components. This "mother" is positionned absolutely, because each elements have to be over different pages.
I noticed that each parallax element wasn't using the acceleration hack, that's why I was wondering whether there was a solution by your side... :/ 

thanks for your quick response.

**Comment by jscottsmith** [comment]
Thanks for the explanation but like I said I'll need to see the code to provide any useful advice. There's far too many factors to consider otherwise. :)

Let me know if you can't provide the repo or site.

**Comment by csantiago132** [comment]
@CYB3RL1F3 delete the old service worker (if you have one) and try again, sometimes the old cache conflicts with the new one. I had the same situation and solved it by doing so. There's a Chrome plugin called Clear Service Worker that would help. 

CC: @jscottsmith

**Comment by jscottsmith** [comment]
@csantiago132 Interesting, I suppose that could be an issue if he has a service worker too. Not sure what his setup looks like though.

**Comment by CYB3RL1F3** [comment]
I'm not using any service worker. Anyway, no problem at all with chrome, the issue is with Safari, only Safari... :/

**Comment by jscottsmith** [comment]
Are you using v1? Just wondering because the v2 alpha uses the IntersectionObserver which hasn't been implemented in Safari and can result in some stuttering from the polyfill. 

Would you mind setting up a repo that reproduces the choppyness? I'd be interested in taking a look as mentioned before :)

**Comment by jscottsmith** [comment]
Ya that sounds like the likely culprit.

And v2 is a prerelease so unless you installed it explicitly with `@alpha` or `@next` you should be on v1 -- I wouldn't use v2 in production yet ;)
