### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by kennethormandy** [jscottsmith/react-scroll-parallax#30]
Hello! I was wondering if you would be open to adding a license file to this project / clarifying what license the component is available under?

Right now, the only information I could find is in the `package.json` (ISC), which I imagine is from the `npm init` default.

Thanks for your hard work on this. By the way—I worked on Surge, so it’s always cool when I stumble across something I’m looking to use that’s using Surge for docs / examples.

**Comment by jscottsmith** [comment]
> (ISC), which I imagine is from the `npm init` default.

Yup, ya got me! 😄 
I'll add an MIT license and get a release out soon. Thanks for the issue.

Oh and Surge is great, thanks for your work!

**Comment by jscottsmith** [comment]
published [v1.3.4](https://github.com/jscottsmith/react-scroll-parallax/tree/v1.3.4)

**Comment by kennethormandy** [comment]
Thanks so much!
