### ISSUE TITLE
styleInner not added to the element

### ISSUE THREAD

**Issue by sayedsaeedhosseini** [jscottsmith/react-scroll-parallax#32]
I was trying to add rotate style to the element with styleInner and StyleOuter but styleInner doesn't add my style to the element. 

``` javascript
<Parallax
className="custom-class"
offsetYMax={-20}
offsetYMin={20}
tag="figure"
styleInner={{ transform: 'rotate(0)' }}
styleOuter={{ transform: 'rotate(80deg)' }}
slowerScrollRate
>
 <div className="my-element" />
</Parallax>
```
* Version: 1.3.5

**Comment by jscottsmith** [comment]
Hi, thanks for the issue.

This is because the `transform` property is used internally by the lib, so your rotations are being overwritten by a translate value.

Closing as I don't intend to change this.
