### ISSUE TITLE
Custom animation

### ISSUE THREAD

**Issue by sayedsaeedhosseini** [jscottsmith/react-scroll-parallax#33]
Add custom animation props to get from/to animation style. 
I need to add style my self, such as rotate or scale style and change their values on scrolling. 
Example: I need to add rotate style to the element from 0deg to 180deg. It must work when page scroll.

**Comment by jscottsmith** [comment]
Thanks, this has been discussed before and will not be supported in v1. 

I do plan to support this in v2. [See here for details](https://github.com/jscottsmith/react-scroll-parallax/issues/15)
