### ISSUE TITLE
how to use this in scrollable div

### ISSUE THREAD

**Issue by adamjw3** [jscottsmith/react-scroll-parallax#34]
title says it all. my elements is in a scrollable div so this isn't working

**Comment by jscottsmith** [comment]
Ya that's not supported. I can look into it.

**Comment by adamjw3** [comment]
@jscottsmith that would great, any idea how long that will take?

**Comment by jscottsmith** [comment]
Hmm, not sure. I'll try to look into it this week. But I've been short on time so don't hold your breath waiting for a release.

**Comment by adamjw3** [comment]
@jscottsmith I might take a look and create a pull request for this if thats ok?

**Comment by jscottsmith** [comment]
Absolutely!

**Comment by eedrah** [comment]
Hmmm, yeah, I was thinking this would scroll relative to where the ParallaxProvider was placed... That is, if my Provider is inside a div, and I scroll that div, then the Parallax works. But if inside my Provider is another div that can scroll, then scrolling that would not affect the parallax.

That's at least how I imagined it to work - but from the above conversation it doesn't work that way?

Any progress on this issue @adamjw3 or @jscottsmith ?

**Comment by adamjw3** [comment]
I have made zero progress on this

**Comment by jscottsmith** [comment]
@eedrah sorry, haven't made much progress. Did start looking into it, but it takes a bit of effort to support scrolling in user specified elements. Currently it works by assuming you're using the default scroll element which is the `<body>` . The provider can be placed anywhere, it just adds the scroll listeners and provides context to children -- it does not affect which area is being scrolled.

**Comment by eedrah** [comment]
Thanks for the reply!

Ah, I see... in the ParallaxController it references the window.innerHeight and pageYOffset and things...

Are you thinking about supporting the upcoming React17? Maybe if you have to re-write the lifecycle methods this would be a good time to adapt the scroll element to support scrolling inside the Provider. 

(https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)

**Comment by jscottsmith** [comment]
Ya this definitely needs a bit of a re-write to address things. Just need to find the motivation ... 🤔

**Comment by jscottsmith** [comment]
added to the latest alpha: #47
