### ISSUE TITLE
problems when viewed on a monitor

### ISSUE THREAD

**Issue by csantiago132** [jscottsmith/react-scroll-parallax#35]
## Expected Behavior

Smooth parallax effect on a 32 in. computer monitor.

## Actual Behavior

not so smooth parallax effect on a 32 in. computer monitor (little jank going on), you can somewhat see the element jumping slightly. I realized this when seeing the same behavior on the demo site after trying to figure out what was wrong with mine.

```
nothing on console log
```

## Steps to Reproduce the Problem
1. I opened the project im working on and saw it on a computer monitor

## Environment
* Version: 1.3.3 & 1.3.5
* Platform: MacOS
* Browser: Safari/Chrome

---

**Comment by jscottsmith** [comment]
Hey, thanks for the issue, but I'll need to see the codebase or a link to provide any advice on this one.

**Comment by csantiago132** [comment]
@jscottsmith no need, it happens when you open the demo site on a big monitor (in this case, 32 in.). I think it can be two things; 1- since the monitor is bigger, you can see the refresh rate and maybe this is what throws me off -or- 2- the resolution/scale config on the monitor makes it look like that. If you open the demo site on a monitor and if it looks ok, then its my monitor.

**Comment by jscottsmith** [comment]
Could also just be a resource issues -- takes more memory/GPU to move bigger images. If you have other resource intense processes/animations on the site or in the background you might want to disable or isolate and see if that's a source.

**Comment by csantiago132** [comment]
yeah, I checked using only my laptop and seems to be the size of the screen, works smoothly on my laptop. I wonder if there's a way to trigger hardware acceleration somehow and maybe try that out. what do you think?

**Comment by csantiago132** [comment]
ok so I tried this out very quickly and i see some improvement (actually, very good) on the monitor

```js

const parallaxStyles = {
  // forcing hardware acceleration from the get go
  transform: 'translate3d(0, 0, 0)'
}

<figure className="project-preview__images">
  <Parallax
    offsetYMax={24}
    offsetYMin={-8}
    offsetXMin={-0.5}
    fasterScrollRate
    tag="span"
    style={parallaxStyles}
  >
    <img
      className="project-preview__images__main-image"
      src={props.mainImage}
      alt={props.project.title.defaultMessage}
    />
  </Parallax>
</figure>
```

im not a guru at css but so far, its an improvement. The idea of this aproach came from:
https://developers.google.com/web/updates/2016/12/performant-parallaxing

its widely supported (caniuse): https://caniuse.com/#search=transform

however, idk if you likr this approach, if you do, ill dig around the code and submit a PR for you to review.

things ill try later
```css
.animClass {
  transform: translate3d(0, 0, 0);
  backface-visibility: hidden;
  perspective: 1000;
}
``` 

and see how that works on the big monitor

**Comment by csantiago132** [comment]
ok im sorry haha, will close now

**Comment by jscottsmith** [comment]
No worries, let me know if you discover any other possible reasons for the jank.

**Comment by yuliwna1** [comment]
Hey @jscottsmith! I'm dealing with the loading issue. The parallax effect is not loading properly when a user first hits the page, it only loads after refreshing the page. What can cause it? Thanks a lot!

**Comment by jscottsmith** [comment]
@yuliwna1 Can you open a new issue and share a link to your project repo or live website? There's also some info about the likely causes of this in the [troubleshooting](https://github.com/jscottsmith/react-scroll-parallax#troubleshooting) section.

**Comment by yuliwna1** [comment]
Thanks a lot! There was a caching problem. Fixed it with update()
