### ISSUE TITLE
Add support for new context API

### ISSUE THREAD

**Issue by jscottsmith** [jscottsmith/react-scroll-parallax#36]
Use React 16.3.0 new [context API](https://reactjs.org/docs/context.html).

- [x] Update the `<ParallaxProvider>` and `<Parallax>` to use new context API
- [x] Document usage of controller methods with new context changes
- [ ] Support old API for accessing controller methods
- [ ] Add new tests/Fix broken tests

**Comment by olegreznichenko** [comment]
Just want to add
`create-react-context` - for supporting old react

**Comment by pavelhamrik** [comment]
Hi guys, I just can't get the context working. 

I'm not using PropTypes to start with, nor do I want to, nor doe the [React docs on Context](https://reactjs.org/docs/context.html#classcontexttype) mention using it like that.

Is there a way to get it working without PropTypes?

I tried, as documented in React docs:
- `MyClass.contextType = ParallaxController;` after declaring MyClass
- `<ParallaxController.Consumer/>` wrapping the component
- `static contextType = ParallaxController;` inside MyClass

`this.context` remains an empty object in these cases.

Is the new API really already supported? Or is there a new new API?

**Comment by jscottsmith** [comment]
New API is not supported, sorry. Hoping to finish an alpha soon using new API and fixing some other issues.

You'll need to use the old context API on the current version.

**Comment by pavelhamrik** [comment]
Understood. Thank you for the answer and your effort in upgrading the lib!

**Comment by jscottsmith** [comment]
will fix in v2. See #47
