### ISSUE TITLE
Disable Scroll Effects on Mobile

### ISSUE THREAD

**Issue by nicelemon** [jscottsmith/react-scroll-parallax#38]
## Trouble Disabling on Mobile

Hi! I've experienced some layout issues on a few of my devices and was hoping to disable the scrolling effects on mobile. I noticed you'd mentioned this as a best practice in the readme and was hoping you might be able to recommend a way to implement. Thanks!

**Comment by csantiago132** [comment]
@nicelemon I did this little codesabox to show it to you instead if trying to explain it here, this is (at least)how im doing it

Theres an event listener to constantly check if the window is being resized, and if it gets resized, itll change your value. hope this helps! 

https://codesandbox.io/s/5z3x61qqxk

**Comment by csantiago132** [comment]
Or set the prop to “true” based on window.width, up to you

**Comment by jscottsmith** [comment]
@nicelemon Yep, as @csantiago132 suggested and demonstrated, adding a resize listener checking the window width and updating the disabled prop is the simplest way and how I would approach it.

**Comment by nicelemon** [comment]
@csantiago132, can't thank you enough for the quick and detailed response. Passing it as a boolean worked perfectly for my setup! @jscottsmith, thanks for the awesome plugin and for weighing in!

**Comment by csantiago132** [comment]
@nicelemon no problem! glad I could help!

**Comment by JayBox325** [comment]
Would be interested to see an example of this using Hooks as someone that is new to React.

**Comment by jscottsmith** [comment]
@JayBox325 I'd recommend something like `react-responsive` then use a hook to disable parallax when a media query is met.

Example:  https://codesandbox.io/s/react-scroll-parallax-disabled-on-mobile-33gysv?file=/src/Example.tsx:0-406

```
import { useParallax } from "react-scroll-parallax";
import { useMediaQuery } from "react-responsive";

import "./styles.css";

export function Example() {
  const isMobile = useMediaQuery({ query: "(max-width: 640px)" });
  const parallax = useParallax<HTMLDivElement>({
    scale: [1, 2],
    disabled: isMobile
  });
  return (
    <div className="test" ref={parallax.ref}>
      Test
    </div>
  );
}
```

**Comment by JayBox325** [comment]
@jscottsmith that's amazing, I actually did something very similar, but I'm using the components instead. This is me making a reusable container that parallaxes due to it being needed on a few different other elements (will be making the speed and which breakpoint is stops a prop that can be passed):

```
import { Parallax } from "react-scroll-parallax";
import { useMediaQuery } from 'react-responsive';
import breakpoints from "@/utils/helpers/breakpoints"; // object of all of my screens to match Tailwind

function ParallaxContainer(props) {

    const {
        children,
        className,
        speed = 6
    } = props || {}

    const isDesktop = useMediaQuery({ query: `(min-width: ${breakpoints.lg}px)` })
    
    return (
        <Parallax className={className} disabled={isDesktop} speed={speed}>
            {children}
        </Parallax>
    )
}

export default ParallaxContainer
```

And this seems to work on first render, but doesn't reset it on resize?
