### ISSUE TITLE
Deprecated lifecycle hooks

### ISSUE THREAD

**Issue by olegreznichenko** [jscottsmith/react-scroll-parallax#40]
## Feature Request

https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html
It will be good to migrate to new hooks.

https://github.com/jscottsmith/react-scroll-parallax/blob/master/src/components/ParallaxProvider.js#L20
https://github.com/jscottsmith/react-scroll-parallax/blob/master/src/components/Parallax.js#L69

**Comment by jscottsmith** [comment]
will fix in v2: see #47
