### ISSUE TITLE
Sometimes it is useful to use a negative value.

### ISSUE THREAD

**Issue by romankrebs** [jscottsmith/react-scroll-parallax#41]
https://github.com/jscottsmith/react-scroll-parallax/blob/9bc2b3b7149c82a46b335b967ae44a435ab16bfb/src/utils/propValidation.js#L38-L42
I have to make a monkey patch to remove restrictions when using negative offsetMax values. Perhaps we remove these limits?
I can do PR :)

**Comment by jscottsmith** [comment]
You can use the [`slowerScrollRate`](https://github.com/jscottsmith/react-scroll-parallax#parallax-props) prop, it internally flips the values which is probably what your are trying to achieve. I won't do this in the next version because it's confusing, but leaving it as is for now. Thanks.
