### ISSUE TITLE
ParallaxBanner Children not displayed

### ISSUE THREAD

**Issue by Krex0r** [jscottsmith/react-scroll-parallax#42]
Hello, i'm very new to web dev.

My _ParallaxBanner_ background image works,
but the **children** (title and subtitle) are not working, like if the image was on them.
Is it a problem with CSS?

```
import React from 'react';
import { ParallaxBanner } from 'react-scroll-parallax';

import './index.css';
import testHeaderImg from '...';

class ProjectHeader extends React.PureComponent {
  render() {
    return (
      <div className="project-header">

        <ParallaxBanner
          className="project-header-parallax-banner"
          layers={[
            {
              image: testHeaderImg,
              amount: 0.6,
              slowerScrollRate: true,
            }
          ]}
          style={{
            height: '900px',
          }}
        >
          <h3>Project TITLE</h3>
          <h5>Project SUBTITLE</h5>

        </ParallaxBanner>

      </div>
    );
  }
}

export default ProjectHeader;
```

Thank you for your time

**Comment by Sleskesty** [comment]
it looks like this is fixed by changing your child element's css if you look at the source code in the stories file it pulls the text forward with a class in the scss file

**Comment by jscottsmith** [comment]
@Krex0r If you want the title/subtitle to be above the banner you will need to include some custom css, or you could include additional layers in the banner, something like:

```
const layers = [
    {
        image: testHeaderImg,
        amount: 0.6,
        slowerScrollRate: true,
    },
    {
        children: <h3>Project TITLE</h3>,
        amount: 0.5,
        slowerScrollRate: true,
    },
    {
        children: <h5>Project SUBTITLE</h5>,
        amount: 0.4,
        slowerScrollRate: true,
    },
];
```

See the [stories](https://github.com/jscottsmith/react-scroll-parallax/blob/master/stories/ParallaxBanner/ParallaxBanner.stories.js) for other examples

**Comment by JosephAntony1** [comment]
This still isn't working for me :( 

`render() {
    const layers = [
      {
        image:
          "https://s3-us-west-2.amazonaws.com/s.cdpn.io/105988/banner-background.jpg",
        amount: 0.5
      },
      {
        image:
          "https://s3-us-west-2.amazonaws.com/s.cdpn.io/105988/banner-foreground.png",
        amount: 0.1
      },
      {
        children: <h5>Project SUBTITLE</h5>,
        amount: 0.4,
        slowerScrollRate: true
      }
    ];
    return (
      <ParallaxProvider>
        <div className="App">
          <div className="vertical">
            <div className={styles.bannerContainer}>
              <ParallaxBanner
                className={styles.bannerBg}
                layers={layers}
                style={{ height: "200vh" }}
              />
            </div>
          </div>
        </div>
      </ParallaxProvider>
    );
  }`

**Comment by jscottsmith** [comment]
@JosephAntony1 What's not working?

Open a new issue with a live link and/or your git repo and describe the problem  – otherwise I can't help.

**Comment by JosephAntony1** [comment]
Understood, I probably won't because I got it working with css, but adding text as a child layer to the banner it wasn't showing up on top of the background, I think it was underneath.

**Comment by jscottsmith** [comment]
@JosephAntony1 Yep, using layer children applies no style. It's a flexible way to let the user decide how it looks which it seems that you were able to do.

**Comment by JosephAntony1** [comment]
So you can't style things inside the layers array even if you wanted to? Thanks for your help and the library btw.

**Comment by jscottsmith** [comment]
You can style them just like any other DOM element in React. 

What I meant by "applies no style" was that `react-scroll-parallax` does not alter the styles of the elements passed as `children` in layers. 

So, you could use inline styles:

```
{
        children: (<h5 style={{ fontSize: 48, color: 'blue' }}>Project SUBTITLE</h5>),
        amount: 0.4,
}
```
or classes from a stylesheet

```
{
        children: (<h5 className="my-styles">Project SUBTITLE</h5>),
        amount: 0.4,
}
```
