### ISSUE TITLE
React prallax scroll background video

### ISSUE THREAD

**Issue by expertup** [jscottsmith/react-scroll-parallax#45]
I need do page with scroll parallax video background. I found this example:
[link](http://react-scroll-parallax-v1.surge.sh/?selectedKind=%3CParallaxBanner%3E&selectedStory=with%20a%20video&full=0&addons=1&stories=1&panelRight=0)
But I can't found source for this example.

This is My code:

< ParallaxProvider >

 		<Parallax
 			style={{margin: "0 !important;"}}
 			offsetYMax={200}
 			offsetYMin={-200}
 			slowerScrollRate
 			tag="div">
 			
 				<video autoPlay loop id="video-background" muted plays-inline style={{width:"100%",height:"100%"}}>
 				  <source src="./backgroung_massage.mp4" type="video/mp4" />
 				</video>
 		</Parallax>
 			<div>
 				<br/>
				<br/>
 				<br/>
 				<br/>
 				<br/>
 				<br/>
 				<br/>
 				<br/>
 				<br/>
 				<br/>
 				<br/>
 				<br/>
 				<br/>
 				<br/>
				<br/>
 				<br/>
 				<br/>
 				<br/>
 				<br/>
 				<br/>
 				<br/>
 				<br/>
 				<Search  />
 			</div>
 < /ParallaxProvider >

Problem is, that 'Parallax' isn't background 'div'. How need look template for parallax video as background, ang other elements as normaly scroll?

**Comment by jscottsmith** [comment]
Source code is here: https://github.com/jscottsmith/react-scroll-parallax/blob/master/stories/ParallaxBanner/ParallaxBanner.stories.js#L84
