### ISSUE TITLE
Use of px unit

### ISSUE THREAD

**Issue by nagman** [jscottsmith/react-scroll-parallax#46]
Hi,

I can't figure out how to use the `px` unit with the `<Parallax>` component.

When I do this : `<Parallax offsetYMin="-60px">`, I get the following error:
```
Uncaught Error: Must provide matching units for the min and max offset values of each axis
```

**Comment by jscottsmith** [comment]
Hey, try this:

```
<Parallax offsetYMin="-60px" offsetYMax="0px" />
```

Offsets default to percent if no unit is passed.
