### ISSUE TITLE
Parallax Not working on Initial Loading

### ISSUE THREAD

**Issue by rajanizwt** [jscottsmith/react-scroll-parallax#48]
Hello @jscottsmith , Thanks for this good library

Parallax is not working on initial loading when i resize window then parallax was working properly I don't know why this issue was coming..

Also i have add ParallaxProvider in my App.js

```
import React, { Component } from 'react'
import { Parallax } from 'react-scroll-parallax'

class TestComponent extends Component {
  render() {
    return (
      <Parallax className="custom-class" y={[-20, 20]} tagOuter="figure">
        <Image src="/image.jpg" />
      </Parallax>
    )
  }
}

export default TestComponent
```

**Comment by jscottsmith** [comment]
You need to update the controller when the image loads. Values are cached when the component mounts but the image probably hasn't loaded. It's in the README.

https://github.com/jscottsmith/react-scroll-parallax#usage
https://github.com/jscottsmith/react-scroll-parallax#example-usage-of-context
https://github.com/jscottsmith/react-scroll-parallax#troubleshooting
