### ISSUE TITLE
Opacity prop

### ISSUE THREAD

**Issue by JulianJorgensen** [jscottsmith/react-scroll-parallax#5]
Really love this library. Great job!

Wondering if you've been considering implementing support for Opacity fade based on scroll as well? I think that'd make this library very complete.

Cheers

**Comment by jscottsmith** [comment]
Thanks, @JulianJorgensen 

I don't have any plans of adding direct support for opacity, however I have thought about adding a prop function to the <Parallax /> component that would return the scroll position of the element. By scroll position I mean a value ranging from `0` to `1` that represents the element's current position in the viewport. That value could then be used to change any properties as needed. Something like this as a quick example:

```
<Parallax
    didUpdate={scroll => updateOpacity(scroll)}
/>
```
Regardless of implementation it's probably a valid use case to be able to use scroll to affect more than just x/y offsets. I'll consider it more going forward. Track any updates to this [here](https://github.com/jscottsmith/react-scroll-parallax/projects/1)

**Comment by JulianJorgensen** [comment]
@jscottsmith ah yes that makes total sense! Currently I've been using my own component to track scroll position through Redux. However, I suspect it is far from optimized, and would much prefer your solution above.

Not sure why there's such a scarcity of Scroll-based components/libraries for React. I know you wrote Parallax is soo not 2017 (hehe!) but I think they still have a place - specially if we can connect other CSS properties than X and Y.

Anyway, thanks a bunch J!

**Comment by oyeanuj** [comment]
@JulianJorgensen I'm in the same boat as you, and am curious where you ended up with this?

**Comment by JulianJorgensen** [comment]
@oyeanuj I ended up implementing my own scroll-based opacity. Its probably not as good as this one, but does the job for now.. I still use this library and would love for it to have the opacity prop as well :-)

**Comment by oyeanuj** [comment]
@JulianJorgensen could you share the rough contours or a gist of your solution?

@jscottsmith do let us know when you add the callback returning scroll position from 0 to 1 as the scroll happesn! it would be super useful for this case!

**Comment by JulianJorgensen** [comment]
@oyeanuj Yesterday I attempted to extend this library so you can pass in a "fadeSpeed" prop. I didn't have time to do a full Pull Request, so just sharing you my 2 gists.

1. Update `_setParallaxStyles` in ParallaxController.js (https://gist.github.com/JulianJorgensen/d70d5b33bf30cadae26f94a455053b3c)

2. Update Parallax.js `componentDidMount` and `componentWillMount` (https://gist.github.com/JulianJorgensen/0d5fa50cef01bf362dba240892ef0ed9)

3. Now you can pass in "fadeSpeed" as a prop. The number can be a bit tricky, but I had great results with `fadeSpeed={1.55}`. 

You can probably modify the code to be more elegant or easier to use. If you do, please share your code.

**Comment by lipenco** [comment]
Would it be possible to make a pull request and add it to the release?

**Comment by oyeanuj** [comment]
@jscottsmith Just checking in to see if adding the function providing scroll position is still on the radar? And/or if @JulianJorgensen's gists above can be used for the same?

**Comment by jscottsmith** [comment]
Ya, I'm still not planning to add opacity support to this version. I've left this open to gauge interest in such a feature and to keep myself motivated in re-writing this package as a [v2](https://github.com/jscottsmith/react-scroll-parallax/tree/v2) that will be much more flexible and provide additional scroll effects like `opacity`. It's still not ready for a release but hoping to get a lot of work done on it this week and get some demos up and running.

**Comment by lsirivong** [comment]
Just want to say this library looks great, but agreed something with a generic 0 - 1 value would be great for our use case. Encouraging you keep on that v2 👏

**Comment by harshayburadkar** [comment]
+1 for the scroll position function or at the least support for opacity prop. Many designs have fading effect based on the scrolling of the page.

**Comment by jscottsmith** [comment]
@harshayburadkar and those wanting opacity effects -- does [this v2 demo](http://react-scroll-parallax.surge.sh/?knob-A%3A%20Opacity%201=1&knob-A%3A%20Opacity%202=0&knob-B%3A%20Opacity%201=0&knob-B%3A%20Opacity%202=1&selectedKind=Parallax&selectedStory=with%20opacity%20props&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs) solve your individual use cases? It simply allows you to move from one `opacity` value to another over the course of the elements visibility in the viewport, just like the offsets work in v1. This can be combined with any other effect too.

If your use case is more complex than this let me know. I'm curious to understand more about what people are trying to achieve.

**Comment by jscottsmith** [comment]
See #15
