### ISSUE TITLE
TypeScript declaration file

### ISSUE THREAD

**Issue by ozio** [jscottsmith/react-scroll-parallax#51]
## Feature Request

People can't use this library in their TypeScript projects, because there is no [TypeScript declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html). Usually, for me it's easier to make own typings, but making typings for this project is more complex and takes more time then I can spend on it right now.

TypeScript becomes very popular. Following [the last State of JavaScript survey results](https://2018.stateofjs.com/javascript-flavors/typescript), almost half of participants using TypeScript and almost third of participants interested in it.

**Comment by jscottsmith** [comment]
@ozio thanks, I can look into this. I haven't used TypeScript much but do see the value in it.

I'm unfamiliar with the ecosystem revolving around TypeScript projects though -- wouldn't there be an easy way to integrate this without adding types to all functions, vars, etc? Like declaring `any` types for everything. Doesn't provide type safety but perhaps it can make the lib work with TypeScript projects while proper typing is added.

**Comment by ozio** [comment]
OK, I'll try to solve it. But I'm not sure when.

**Comment by jscottsmith** [comment]
Thanks, I will also look into it soon.

**Comment by ricokahler** [comment]
@jscottsmith Are you open to PRs? I just wrote some typings

**Comment by SoaresMG** [comment]
@ricokahler perhaps create it on [@types](https://github.com/DefinitelyTyped/DefinitelyTyped#readme) global namespace.

I can help if anyone is interested.

**Comment by jscottsmith** [comment]
@ricokahler Yes! PRs appreciated. Especially if there is a simple update to at least get the lib working with TypeScript projects.

**Comment by ricokahler** [comment]
@jscottsmith https://github.com/jscottsmith/react-scroll-parallax/pull/53

**Comment by jscottsmith** [comment]
Published [2.0.6](https://github.com/jscottsmith/react-scroll-parallax/tree/v2.0.6) with typings. Let me know if there's issues
