### ISSUE TITLE
support webp as image banner

### ISSUE THREAD

**Issue by dohomi** [jscottsmith/react-scroll-parallax#52]
Hello,

If layers image consist of a WebP image format they are not been rendered with `ParallaxBanner`. I am not sure if this is actually a feature or bug at the moment. This is an example setup:
```
<ParallaxBanner layers={[image: 'image-url.webp']} /> // not applied as background
<ParallaxBanner layers={[image: 'image:'image-url.jpg']} /> // works
```
Best,
Dominic

**Comment by jscottsmith** [comment]
@dohomi What browser? Support for WebP is still limited https://caniuse.com/#feat=webp

I'd recommend [feature detection](https://modernizr.com/) and pass the appropriate type of `image` prop to the component. Not much I can do about this in the component itself I'm afraid.

**Comment by dohomi** [comment]
Hi @jscottsmith 
I do webp detection and only in use with ParallaxBanner the image is not being loaded. I use an the image proxy this are the URLs maybe its because of the URL schema?
```
path-to-img/filters:format(webp)/account.jpg // does not work
path-to-img/account.jpg
```
Is there maybe an issue of using the `filters:format(webp)` as a string? Thats the syntax of Storyblok image proxy API.
Thanks for your swift response

**Comment by jscottsmith** [comment]
Hmm, I'm not totally following.

Is your code publicly accessible? Might help me understand the issue more clearly. Or put together a simple demo that reproduces the issue. Happy to take a look if so.

**Comment by dohomi** [comment]
@jscottsmith I forgot to wrap the img src as string correctly. All good sorry for the noise and thanks for the excellent component.
