### ISSUE TITLE
Speed control

### ISSUE THREAD

**Issue by visualcookie** [jscottsmith/react-scroll-parallax#54]
## Feature Request

Speed control of a parallax element would be useful, to have different speeds while scrolling. Right now all parallax elements animate with the same speed.

May use-case right now: think of art shapes (lines, triangles, ...) which are on different speed levels (eg. the triangle is on 0.3 and the rectangle on 0.1), this would make the rectangle the slowest and the triangle the fastest while scrolling.

Can only refer to an example made with `react-spring` (can't use `react-spring` in my case, since they do `position: absolute` on each element):
https://codesandbox.io/s/nwq4j1j6lm

---

Maybe this already exists but I haven't found any documentation to it, as when I implemented it, all elements had the same speed levels and would stop after say `20px` of scroll.

**Comment by jscottsmith** [comment]
@visualcookie did you look at the storybook? The API doesn't use a `speed` property but rather start and end offsets. Speed is controlled by increasing those offsets. 

Elements moving at different "speeds":
https://react-scroll-parallax-next.surge.sh/?path=/story/parallax-vertical--linear-y-offsets

Source code:
https://github.com/jscottsmith/react-scroll-parallax/blob/master/stories/Parallax/1_ParallaxVertical.stories.js

> Maybe this already exists but I haven't found any documentation to it, as when I implemented it, all elements had the same speed levels and would stop after say 20px of scroll.

Sounds like a cache issue, or related to your setup:
https://github.com/jscottsmith/react-scroll-parallax#troubleshooting

Link me your repo or site if you want better support. I can only guess otherwise.

**Comment by visualcookie** [comment]
Hey @jscottsmith. I've set-up a sandbox of my use-case right now. It's not quite accurate, but it shows how it's set-up on my website right now.

The issue I'm facing right now:
- Lines not even moving (value changes when looking in DOM)
- Content moving, but positions are getting weirdly misplaced, when playing around with the `y` values

**Comment by jscottsmith** [comment]
@visualcookie I’ll need a link to the sandbox.

**Comment by visualcookie** [comment]
@jscottsmith Oops, sorry, forgot to paste the link.

https://codesandbox.io/s/40nq75p6xw

**Comment by jscottsmith** [comment]
Your styling is causing the issues.

First thing, you won't be able to rotate the parent holding the parallax elements and get expected effects. If you need to rotate with transforms apply the styling to children. 

Using absolute positioning can be tricky. I suggest positioning the parent absolutely and applying parallax effects to a relatively positioned child.

The effects you want are in one of the examples: 
https://github.com/jscottsmith/react-scroll-parallax-examples
https://jscottsmith.github.io/react-scroll-parallax-examples/examples/parallax-example/

Specifically here which uses absolute positioning on parents and parallaxes children:

https://github.com/jscottsmith/react-scroll-parallax-examples/tree/master/examples/parallax-example/components/ShapeField

I'd suggest starting simple with just boxes that parallax then apply appropriate styles to get the desired look you want.
