### ISSUE TITLE
It only works if I start scrolling at top of the website

### ISSUE THREAD

**Issue by leosantacruz** [jscottsmith/react-scroll-parallax#63]
Hi, 
This issue appears in the oficial [DEMO ](https://jscottsmith.github.io/react-scroll-parallax-examples/examples/parallax-example/) and in a new simple project I did myself.

When I start scrolling at the top of the website it works perfectly. But when I start scrolling at the middle of the website and refresh the browser it seems It doesn't work.

It was tested on Chrome 75 and Opera 60

Regards

**Comment by jscottsmith** [comment]
Ya this is kind of an annoying browser feature. I think we may get an API to disable it in the future via `history.scrollRestoration`. See here for [more info](https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration)

Way around it for now:

Add a listener at a high level in your app for when the page fully loads and update the parallax controller so cached values get set at the current scroll state:

```js
window.addEventListener('load', (event) => {
    this.props.parallaxController.update();
});
```

Accessing the controller:
https://github.com/jscottsmith/react-scroll-parallax#parallax-controller-context

**Comment by jscottsmith** [comment]
Let me know if this didn't work.

**Comment by ilyausorov** [comment]
Can confirm that the above proposal worked, but I had to add an additional `window.scrollBy(0,1);` to force a 1px scroll so that the elements reset to their right place.
