### ISSUE TITLE
Unable to work out how to update parallaxController using functional components

### ISSUE THREAD

**Issue by lukebennett88** [jscottsmith/react-scroll-parallax#67]
### Describe the trouble you are having considering the following:

I have a number of images that I am using `react-scroll-parallax` on over a few pages.

On the home page, if I scroll down to the bottom, and then use the website navigation to go to a new page, the parallax image on the next page is position incorrectly.

From reading the documentation on the README, it looks like I need to call the `parallaxController.update()` function to reset the scroll position, but I can't work out how to do that.

In the following example, I have `parallaxController` in my props, but it has a value of `null`

```jsx
import React, { useEffect } from 'react';
import { graphql } from 'gatsby';
import { ParallaxProvider, withController } from 'react-scroll-parallax';
import PropTypes from 'prop-types';

import Layout from '../components/Layout';
import SEO from '../components/SEO';
import HeroNav from '../components/HeroNav';
import Hero from '../components/Hero';
import Why from '../components/Why';
import ServicesSection from '../components/ServicesSection';
import GiftVoucher from '../components/GiftVoucher';
import Contact from '../components/Contact';
import Map from '../components/Map';

const IndexPage = props => {
  console.log(props.parallaxController);
  // useEffect(() => {
  //   window.addEventListener('load', event => {
  //     parallaxController.update();
  //   });
  // }, [parallaxController]);

  return (
    <ParallaxProvider>
      <SEO title="Home" />
      <HeroNav />
      <Hero />
      <Layout>
        <Why />
        <ServicesSection />
        <GiftVoucher />
        <Contact data={props.data} />
        <Map />
      </Layout>
    </ParallaxProvider>
  );
};

IndexPage.propTypes = {
  data: PropTypes.object,
};

export default withController(IndexPage);

export const query = graphql`
  query IndexPageQuery {
    hero: file(relativePath: { eq: "contact.jpg" }) {
      childImageSharp {
        fluid(maxWidth: 3000, quality: 100) {
          ...GatsbyImageSharpFluid_withWebp
        }
      }
    }
    site {
      siteMetadata {
        address
        email
        facebook
        googleMapsLink
        instagram
        phone
        phoneFormatted
      }
    }
  }
`;
```

* What is the expected behaviour of your implementation?
When transitioning between pages, `parallaxController.update()` should be called so that images are in the right place.
* Can you share the repository, live site, or a demo?
  * Repository: https://github.com/phirannodesigns/portdayspa.com.au
  * Live site: https://portdayspa.netlify.com
* Are you seeing any errors or warnings?
No error are showing.
* Any relevant snippets of code you can provide?
Code snippet about shows that `parallaxController` is returning `null`

**Comment by mrhut10** [comment]
on your repo is the problem your having on the master branch @lukebennett88 as i'll checkout it and have a play

**Comment by lukebennett88** [comment]
Sure is @mrhut10

**Comment by mrhut10** [comment]
interesting, i'm getting it work sometimes but not othertimes, i'll look at there code to see if can understand what they are doing. @lukebennett88

**Comment by mrhut10** [comment]
ok, i have something that i think we should try.

they state within [documentation](https://github.com/jscottsmith/react-scroll-parallax#parallaxprovider)
that the parallaxprovider should only be used once in whole app wrapping the root component, whereas you are using it within each page. I will read further to see if that alone is making it unpredictable. however we could use one of gatsby's methods to have it wrap the whole of the gatsby application.

i'll keep playing with

**Comment by lukebennett88** [comment]
I wasn’t sure if that was an issue or not.
I originally had it in my layout component, but since on the home page, the hero component is above the header, it has sense to do it this way.

My main issue, was that I couldn’t access the `update()` method on parallaxController (there is a parallaxController prop, but it returns null.)

**Comment by jscottsmith** [comment]
@lukebennett88 

Accessing the controller in requires using [React's context API](https://reactjs.org/docs/context.html). I'd recommend reading those docs to familiarize yourself with how context works. 

There's a higher order component that will connect to the controller context and pass the controller to your component's props:

https://github.com/jscottsmith/react-scroll-parallax#example-usage-of-context

This must be used in a component nested within the`<ParallaxProvider>` as the provider gives access to context in all child components.

I'm also not sure if calling update on a window load event will fix the issue you are having. It seems related to the following issue #65 which I don't have a solution for.

**Comment by mrhut10** [comment]
@jscottsmith and @lukebennett88 we might need to put a method in the gatsby-browser to catch the route changing event and ask it to update.

also @lukebennett88 i'm about to send you a PR i was hoping you could look at to see if an improvement.

**Comment by jscottsmith** [comment]
@mrhut10 Ya that sounds good as long as that method has access to the controller. Currently you can only access it through context. Appreciate the help on this.

**Comment by mrhut10** [comment]
Ok @jscottsmith currently i've wrapped each page that requires a update in component as below
```js
import React, { useEffect } from 'react';
import { withController } from 'react-scroll-parallax';
import PropTypes from 'prop-types';

const ParalaxUpdate = ({ children, parallaxController, location }) => {
  useEffect(() => {
    if (typeof window !== 'undefined') {
      console.log('running parallax update');
      parallaxController.update();
      return ()=>{console.log("exiting parallax update")};
    }
  }, [parallaxController, location]);
  return <>{children}</>;
};

ParalaxUpdate.propTypes = {
  children: PropTypes.any,
  location: PropTypes.object,
  parallaxController: PropTypes.object,
};

export default withController(ParalaxUpdate);

```

which i believe is working waiting feedback from @lukebennett88 to confirm.

I also tried to do this automatically by using a method to gatsby provides to wrap each page in a element automatically within the gatsby-browswer file/api, however haven't had any success in this as of yet.

feedback appreciated

**Comment by jscottsmith** [comment]
@lukebennett88 Yup makes sense. Strange I had issues with this not working when I was troubleshooting the other Gatsby issue since it's the same idea – update the controller when location changes. 🤷‍♂

**Comment by jscottsmith** [comment]
See #65
