### ISSUE TITLE
Testing Erorr: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by ericnguyen23** [jscottsmith/react-scroll-parallax#68]
I'm running tests with Jest and getting this error when using this library:

`TypeError: Cannot read property 'getBoundingClientRect' of null`

Anyone know why and how I can get it to pass test?

Versions:
Node: v10.15.3
npm: 6.4.1
"react-scroll-parallax": "^2.1.2"

**Comment by jscottsmith** [comment]
You shouldn't be running tests from this library in your own project. I'm guessing it's a Jest setup issue that for whatever reason is capturing the test files from this dependency. 

What's you setup look like? Have a repo?

**Comment by jscottsmith** [comment]
Oh, nvm. Tests aren't even shipped in the package. I guess you're doing some local development.

`getBoundingClientRect` is mocked because jsdom doesn't include the api. 

So it sounds like the mock isn't being used.

Is there a more detailed error log?

**Comment by jscottsmith** [comment]
Need more details to help out -- tests are passing on Travis CI so not sure why you would be getting this error.
