### ISSUE TITLE
Using with Next.js and gives an error for ParallaxProvieder when using useController()

### ISSUE THREAD

**Issue by hrahimi270** [jscottsmith/react-scroll-parallax#79]
## Expected Behavior

Able to use `useController()` in my next.js app.

## Actual Behavior

It throws an error that:

> Error: Could not find `react-scroll-parallax` context value. Please ensure the component is wrapped in a `<ParallaxProvider>`

## Steps to Reproduce the Problem

1. I placed `ParallaxProvieder` in my `_app.js` file.
2. I created my parallax component and it's working fine!
3. I created a `ParallaxCache` component just like the example.
4. I put `ParallaxCache` beside my parallax component and it gives me the error.

## Environment

* Next version: 9.0.5
* Browser: chrome last update

**Comment by jscottsmith** [comment]
@hrahimi270 Thanks for the issue.

I think this because Next js renders on the server and the controller is not available. Check for `typeof window !== 'undefined'` then call the `useController` in `ParallaxCache`. 

Let me know if you need further explanation, or share the repo with me.

**Comment by hrahimi270** [comment]
@jscottsmith Thanks for the reply.
I will test it to let you know.
But if `context` couldn't be found, then how Parallax component works?

**Comment by jscottsmith** [comment]
It shouldn't work on the server (just rendering the html to send to the client), but when React hydrates on the client side the Parallax context will be created and should run fine.

**Comment by jscottsmith** [comment]
To give you a little more context, see the provider which creates the controller and provides it in React context api. 

https://github.com/jscottsmith/react-scroll-parallax/blob/master/src/components/ParallaxProvider.js#L12

**Comment by jscottsmith** [comment]
@hrahimi270 let me know if this doesn't solve your issue.

**Comment by sebinievas** [comment]
@jscottsmith so i'm stepping into this almost 3 months later and i'm experiencing the same issue still. I cannot get a simple example to work for this. I did manage to pull down like an old example from next 4 i believe, from 2018, and that actually worked! But cannot get it to work here. I realize this may be more of a nextjs question, but any more light you can shed would be great.

**Comment by hrahimi270** [comment]
@sebinievas I was able to use this package in my project. Even without `useController()` hook.
What is your problem exactly? can you provide some code here?

**Comment by sebinievas** [comment]
Absolutely, thank you! https://gist.github.com/sebinievas/5f597c5713ef0888a36352964efd90dc

**Comment by hrahimi270** [comment]
@sebinievas Thanks.
There is nothing wrong with your `ParallaxProvider`.
But in the `test.js` file, I'm not sure about using `offsetYMin` and `offsetYMax` props.
As I remember and written in documents, you should use like `y={[ -10, 10 ]}`.
For more information, read this section of the document:
https://github.com/jscottsmith/react-scroll-parallax#parallax-props

**Comment by sebinievas** [comment]
Thank you! I think this is working. I created a brand new project just to
test this out, and it seems to be working! I must have pulled an OLD
example? Sigh... glad its working!

**Comment by dowrow** [comment]
How can I make the useController() hook work with Next.JS if it's server-side generated?

**Comment by matthewkwong2** [comment]
> @hrahimi270 Thanks for the issue.
> 
> I think this because Next js renders on the server and the controller is not available. Check for `typeof window !== 'undefined'` then call the `useController` in `ParallaxCache`.
> 
> Let me know if you need further explanation, or share the repo with me.

Perhaps I missed it, but I think it would be a good idea if you provide the `ParallaxCache` component out of the box. Here is my version of the component. Basically, it is the one mentioned in the doc with the addition of monitoring resize.

Also, would it be a good idea to use `useEffect` instead?

```jsx
import { useController } from "react-scroll-parallax";
import { useLayoutEffect } from "react";

const ParallaxCache = () => {
  const { parallaxController } = useController();

  useLayoutEffect(() => {
    const handler = () => parallaxController.update();
    window.addEventListener("load", handler);

    const resizeObserver = new ResizeObserver(handler);
    resizeObserver.observe(document.body);

    return () => {
      window.removeEventListener("load", handler);
      resizeObserver.unobserve(document.body);
    };
  }, [parallaxController]);

  return null;
};

export default ParallaxCache;
```

**Comment by petr-hajek** [comment]
For me the only solution how to use it with Next.js with page navigation was to include this component on the client side. Strange thing is that it needs the setTimeout to work even if it's 0ms. Hope it helps someone.

```
import { useRouter } from 'next/router';
import { useLayoutEffect } from 'react';
import { useController } from 'react-scroll-parallax';

export const ParallaxCacheFixer = () => {
	const { parallaxController } = useController();
	const router = useRouter();

	useLayoutEffect(() => {
		const handleRouteChange = () => {
			// This timeout is very hacky solution
			setTimeout(() => {
				parallaxController.update();
			}, 0);
		};
		router.events.on('routeChangeComplete', handleRouteChange);
		return () => {
			router.events.off('routeChangeComplete', handleRouteChange);
		};
	}, [parallaxController, router.events]);

	return null;
};
```

**Comment by jscottsmith** [comment]
@petr-hajek apologies for this, there was a bug that I discovered recently when refactoring this to a new version #123. I just published a patch that should fix these hacky `setTimeouts` solutions when calling `parallaxController.update()`. 

Try the patch here `react-scroll-parallax@2.4.1` and LMK if it's still a problem. Thanks!

**Comment by petr-hajek** [comment]
@jscottsmith Fixed, thanks, now it works out of the box for my Next.js app.
