### ISSUE TITLE
horizontal ?

### ISSUE THREAD

**Issue by deesx** [jscottsmith/react-scroll-parallax#8]
As you specify in bold that it is "vertical" on the readme

Not an issue, I might not be that clever finding out by myself, but wondering how you were achieving the following horizontal thing that was also listed in the readme : https://jscottsmith.github.io/react-scroll-parallax/examples/parallax-example/

**Comment by jscottsmith** [comment]
@deesx *Vertical* is emphasized in the readme to refer to the direction of scrolling that the package supports. This means it does not support horizontal scrolling. 

The example you linked is a vertically scrolling site with horizontal offsets applied to elements. Nothing clever is happening and you should be able to achieve a similar effect quite simply by providing `offsetXMax` and `offsetXMin` to the `<Parallax> component like so:

```
<Parallax
    offsetXMax={20}
    offsetXMin={-20}
>
    <div>content here</div>
</Parallax>
```

Those props are [documented here](https://github.com/jscottsmith/react-scroll-parallax#parallax-component-props). Or take a look at the source to the [example here](https://github.com/jscottsmith/react-scroll-parallax-examples/blob/master/examples/parallax-example/components/IntroCopy/IntroCopy.js#L17)

Closing this as I don't have any plans to support horizontal scrolling in this version.
