### ISSUE TITLE
ParallaxBanner left to right

### ISSUE THREAD

**Issue by soares-lu** [jscottsmith/react-scroll-parallax#85]
There any way to use Banner animation left/right instead of top/bottom? I'm using a horizontal scroll and if I can use this banner with X parallax will be awesome!

**Comment by jscottsmith** [comment]
No, not currently.

You could create your own! The `ParallaxBanner` is just a wrapper around the `Parallax` component that controls some additional style to 'expand' the background image to cover the distance it will move.

Check the source:

https://github.com/jscottsmith/react-scroll-parallax/blob/master/src/components/ParallaxBanner.js

I will look into supporting this in the future but if you need it now you're better off just creating your own.

**Comment by soares-lu** [comment]
Alright, thanks, man! I got it!

**Comment by aktn** [comment]
For anyone counter like this in the future, this might save your time ;)
`
const containerStyle = {
  position: "relative",
  overflow: "hidden",
  width: "100%",
};

const ScrollParallax = () => {
  return (
    <div style={{ ...containerStyle, height: "500px" }}>
      <Parallax x={[0, -30]}>
        <img
          style={{
            backgroundPosition: "center",
            backgroundSize: "cover",
          }}
     src="https://cdn.dribbble.com/users/2060/screenshots/6996102/media/26d84f8a1566a719dcc1f66c9dcf7483.jpg"
        />
      </Parallax>
    </div>
  );
};
`

**Comment by jscottsmith** [comment]
Planning to support in the new version #123
