### ISSUE TITLE
ScrollAxis change resizing window

### ISSUE THREAD

**Issue by soares-lu** [jscottsmith/react-scroll-parallax#86]
I want to change scrollAxis of <ParallaxProvider /> when resizing the window (using useState). But every time window size changes, this element not re-render again. This is not possible to do?

I want to change parallax animation for mobile devices... Can anyone help me?

**Comment by jscottsmith** [comment]
Guessing since I need more context, but you can try adding a `key` to the `ParallaxProvider` that changes when you want the axis to change. This should force React to remount the element and setup a new parallax controller.

**Comment by jscottsmith** [comment]
@soares-lu Did you find a solution?

**Comment by soares-lu** [comment]
> @soares-lu Did you find a solution?

Sorry for the delay with the answer. But I got it!

I put an if in the Provider and it worked. Just like that:

useEffect(() => {
  screenSize.width <= 1024 ? set('vertical') : set('horizontal');
}, [screenSize.width])

if (!orientation) {
  return <div />
} else {
  return (
    <ParallaxProvider scrollAxis={orientation}>
    </ParallaxProvider>
  )
}
