### ISSUE TITLE
parallaxController.update needs to be called twice to work

### ISSUE THREAD

**Issue by axeen** [jscottsmith/react-scroll-parallax#88]
## Expected Behavior

I should only have to run parallaxController.update() once

## Actual Behavior

After loading images, the cached position of the parallax element is wrong, so parallaxController.update needs to be called on load. Calling it once doesn't do anything though, running it twice results in the expected behavior. I tried putting it in a setTimeout instead of listening to load, and it logs my message but doesn't do anything unless called twice.

I made a codedandbox example, and it shows this behavior as well: https://codesandbox.io/s/optimistic-pine-nedre?file=/src/ParallaxCache.js

## Environment

* Version: 2.3.2
* Platform: Mac
* Browser: Chrome

**Comment by axeen** [comment]
Hmm, it seems what I described only happens in the codesandbox example if the console (actual browser console) is open. On my local project, having the console open doesn't seem to matter though.

**Comment by LinusGeffarth** [comment]
I too have this issue when using in combination with `ParallaxBanner`. Can't fix it with double-update call, though, unfortunately.

**Comment by Gurenax** [comment]
My workaround is to call `parallaxController.update()` after the image has loaded, but also calling it on `useEffect` before that. The reason is that it will not give out the correct value for CSS transform if the image has not yet finished loading.

```
  const { parallaxController } = useController();

  useEffect(() => {
    parallaxController.update();
  });

  const onImageLoad = () => {
    parallaxController.update();
  }

  return (
    <Container>
      <Parallax y={[-20, 20]}>
        <img src={src} onLoad={onImageLoad}/>
      </Parallax>
    </Container>
  )
```
