### ISSUE TITLE
Feature request: other transforms based on scroll progress

### ISSUE THREAD

**Issue by kmjennison** [jscottsmith/react-scroll-parallax#89]
## Feature Request

I'm curious if this library could allow for arbitrary transforms to make the parallax behavior even more flexible. I was looking for the ability to change the size of an element on scroll: to zoom in as the element moved into view. As far as I could tell, it's not currently possible to change anything other than the x-y position of the element.

If the `<Parallax />` component or child element had access to the "% moved" (progress through its movement) value, then the user could use that value to implement any transforms or style changes.

## Proposed Changes

One approach is to use a render prop that receives the "% moved". Another React parallax library [does this](https://github.com/rrutsche/react-parallax#renderlayer). However, I imagine there could be performance concerns about constantly re-rendering in React.

Another approach would be to let the user specify a function that, provided the "% moved" value, returns raw styles. This would be similar to how the `translate3d` transform is set [here](https://github.com/jscottsmith/react-scroll-parallax/blob/0d93c89f15f6a20338176ec775cd5f9fbcc72160/src/helpers/elementStyles.js#L17). For example, maybe there's a prop like:
```jsx
<Parallax
    getTransformStyle={progress => `rotate(${progress * 3}deg)`}
/>
```
Then, the library could merge that with the `translate3d` transform string when updating. We could also generalize this to set arbitrary style values with something like a `getStyle` prop.

Thoughts?

**Comment by chenchenalex** [comment]
@jscottsmith  just to follow up, what is the progress for this feature enhancement? thanks!

**Comment by andrii-sirko** [comment]
Hi, @jscottsmith! 
I have created a PR for implementing this feature: https://github.com/jscottsmith/react-scroll-parallax/pull/117

Let me know if can help more with it.

**Comment by jscottsmith** [comment]
Will support this in the new version #123
